import Header from './components/header/Header'
import Footer from './components/footer/Footer'
import './globals.css'

export const metadata = {
  title: '한국ICT인재개발원',
  description: 'Generated by create rhj',
  icons:{
    icon: '/images/ict_favicon.png'
  }
}

export default function RootLayout({ children }) {
  return (
    <html>
      <body>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  )
}
